"""paramark の基礎データ構造とユーティリティ。"""

from .geometry import (
    ArcTo,
    Bounds,
    Circle,
    ClosePath,
    GraphicObject,
    Group,
    LayeredGraphic,
    LineTo,
    MoveTo,
    Path,
    Point,
    Polygon,
    Polyline,
    Rectangle,
    Style,
)
from .metadata import MetadataDict, MetadataValue, merge_metadata, metadata_dict, prefixed_metadata
from .naming import build_parametric_name, format_mm_token, format_number_token
from .packing import PackedItem, PackingItem, PackingResult, pack_shelves
from .svg import SvgDocument, render_svg_document, save_svg
from .transforms import AffineTransform, compose, rotate, scale, translate
from .units import (
    A4,
    A4_MM,
    BASE_MODEL_SCALE,
    POSTCARD,
    POSTCARD_MM,
    Scale,
    SheetSize,
    full_size_length_mm,
    rescale_model_length_mm,
    scaled_length_mm,
)

__all__ = [
    "A4",
    "A4_MM",
    "BASE_MODEL_SCALE",
    "POSTCARD",
    "POSTCARD_MM",
    "AffineTransform",
    "ArcTo",
    "Bounds",
    "Circle",
    "ClosePath",
    "GraphicObject",
    "Group",
    "LayeredGraphic",
    "LineTo",
    "MetadataDict",
    "MetadataValue",
    "MoveTo",
    "PackedItem",
    "PackingItem",
    "PackingResult",
    "Path",
    "Point",
    "Polygon",
    "Polyline",
    "Rectangle",
    "Scale",
    "SheetSize",
    "Style",
    "SvgDocument",
    "build_parametric_name",
    "compose",
    "format_mm_token",
    "format_number_token",
    "full_size_length_mm",
    "merge_metadata",
    "metadata_dict",
    "pack_shelves",
    "prefixed_metadata",
    "render_svg_document",
    "rescale_model_length_mm",
    "rotate",
    "save_svg",
    "scale",
    "scaled_length_mm",
    "translate",
]
